::I18n.translate takes keyword arguments
Ruby v3 is failing with the following exception since :I18n.translate takes the options as keyword arguments and not a hash:
~~~
ArgumentError: wrong number of arguments (given 2, expected 0..1)
            /Users/rmorrison/.rvm/gems/ruby-3.0.0/gems/i18n-1.8.7/lib/i18n.rb:195:in `translate'
            /Users/rmorrison/.rvm/gems/ruby-3.0.0/gems/mongoid-7.2.0/lib/mongoid/errors/mongoid_error.rb:51:in `translate'
            /Users/rmorrison/.rvm/gems/ruby-3.0.0/gems/mongoid-7.2.0/lib/mongoid/errors/mongoid_error.rb:66:in `translate_problem'
            /Users/rmorrison/.rvm/gems/ruby-3.0.0/gems/mongoid-7.2.0/lib/mongoid/errors/mongoid_error.rb:25:in `compose_message'
            /Users/rmorrison/.rvm/gems/ruby-3.0.0/gems/mongoid-7.2.0/lib/mongoid/errors/document_not_found.rb:32:in `initialize'
            /Users/rmorrison/.rvm/gems/ruby-3.0.0/gems/mongoid-7.2.0/lib/mongoid/reloadable.rb:26:in `new'
            /Users/rmorrison/.rvm/gems/ruby-3.0.0/gems/mongoid-7.2.0/lib/mongoid/reloadable.rb:26:in `reload'
~~~